### ISSUE TITLE
Generate new APK on Github action

### ISSUE THREAD

**Issue by enzoftware** [enzoftware/hotel_booking_app#11]
Generate a `.apk` file in every commit to some branch

**Comment by Mastersam07** [comment]
Kindly assign this to me

**Comment by enzoftware** [comment]
It's all yours @Mastersam07 !

**Comment by enzoftware** [comment]
Any update?

**Comment by Mastersam07** [comment]
Would definitely send a pull request. The country here has been upside down this period. Peaceful protests turned bloody and all, curfew and no power also.

However, I'll send a PR soon.

**Comment by Mastersam07** [comment]
@enzoftware I just sent a PR #14
